### ISSUE TITLE
Item interval time setting

### ISSUE THREAD

**Issue by Futyn-Maker** [tsengwoody/Access8Math#12]
Hello!

Please, explaine me, how must this setting work in general? I don't note any changes when I regulate this. I assume that it should adjust pauses between math elements, but it doesn't work.

**Comment by tsengwoody** [comment]
This setting may not work because it is related to the synth driver used. 
What synth driver you use? I test SAPI synth driver and can work correctly.
This setting value have no standard value, just look at the personal feeling setting.

**Comment by Futyn-Maker** [comment]
OK, thanks. With SAPI5 and ESpeak this setting works correctly, but I normally use Vocalizer Expressive driver and with this synth there're no intervals.

**Comment by tsengwoody** [comment]
What version NVDA and Vocalizer Expressive driver using?
Vocalizer Expressive driver 3.1.2 for NVDA 2019.3+ already have break command.
https://www.tiflotecnia.net/Instal/vocalizer_expressive_driver-3.1.2.nvda-addon
So VE 3.1.2 is work correctly

**Comment by Futyn-Maker** [comment]
I use the old version of Vocalizer (3.0.12) because i don't like the sound of some voices in new versions. I've understood about synth drivers, so, the problem is in the old version. Thanks

**Comment by Futyn-Maker** [comment]
Hello! I need to reopen this issue to ask if it is possible to develop interval times for RHVoice synthesizer (https://github.com/olga-yakovleva/rhvoice). It contains a lot of languages and is very popular in Russia and other countries.

Thanks

**Comment by Futyn-Maker** [comment]
@tsengwoody Hello! Could you, please, explaine, how to add support of time intervals for new synthesizers? I didn't find any code that do it, but I want to add support of interval times for RHVoice and NewFon synthesizers as they/re popular.

**Comment by tsengwoody** [comment]
Support of time intervals break(pausing between item and item) cannot be achieved by Access8Math.
Access8Math just send break speech command to synthesizer and synthesizer should properly handle break speech command.
