### ISSUE TITLE
German locales

### ISSUE THREAD

**Issue by Pit-Storm** [tsengwoody/Access8Math#13]
Dear  @tsengwoody !

great Plugin and thank you for your work 👍 

Can you give me some explanation how one would add a translation for e.g. german?

I found two folders where translations has been defined:
1. [This one for the addon menu and so on](https://github.com/tsengwoody/Access8Math/tree/master/addon/locale):\\
It is really straight forward and it is clear whar to do for another translation.
2. And [this one for the math rules and unicode dicts](https://github.com/tsengwoody/Access8Math/tree/master/addon/globalPlugins/MathMlReader/locale):\\
Can you give some explainatioin how the structure of these two file is and how they work in conjunction with the code?

Did I miss some localization files?

Would be great to hear from you, so that I can provide a german locale.

Kind regards!

**Comment by tsengwoody** [comment]
Yes. localization files is nvda.po and math.rule, unicode.dic.
https://github.com/tsengwoody/Access8Math/blob/master/Access8Math.pot
using this file and importing poedit to edit.
math.rule, unicode.dic can be edited by GUI setting.
I suggest using it to edit. (math rule...->math.rule file, unicode dictionary...->unicode.dic)
I suggest using the ui in the addon to add and edit your language.
1. New language adding...->choice your language->OK
2. General settings...->choice your language->OK
3. Using unicode dictionary... and math rule... UI to edit and click OK button to save it.

**Comment by tsengwoody** [comment]
What version NVDA and Vocalizer Expressive driver using?
Vocalizer Expressive driver 3.1.2 for NVDA 2019.3+ already have break command.
https://www.tiflotecnia.net/Instal/vocalizer_expressive_driver-3.1.2.nvda-addon
So VE 3.1.2 is work correctly
