### ISSUE TITLE
Add separate rule for logarithms

### ISSUE THREAD

**Issue by Futyn-Maker** [tsengwoody/Access8Math#14]
Hello!

I think we need in separate math rule to treatment of logarithms. It's known that the base of logarythm function is written as subscript, but it isn't spoken like a usual digit/variable with subscript.
I believe that it would be very useful if Access8Math had separate rule for log-functions. Now I can set ```"log"``` word in unicode.dic, but not a rule to spoken a base and a sub-logarithmic expression.

Thanks

Andrey

**Comment by tsengwoody** [comment]
OK, I will add rule for logarithms.
