### ISSUE TITLE
Translating of operator-names

### ISSUE THREAD

**Issue by Futyn-Maker** [tsengwoody/Access8Math#18]
Hello!

I use the unicode.dic dictionary to translate operator-names, such as `sin`, `cos`, `tan` and so on. But the problem is that when this name is the part of other name, it's spoken incorrectly.

For example, I have such rule:
```tan	тангенс	none```
And if the operator-name is `tan`, it's OK. But if I, for example, see `arctan`, I hear something like "arcтангенс" (two alphabets are merge into one word).

Of course, I can add rule `arctan` befor `tan` and it should solve the problem, but I cannot find all cases when one operator is the part of other one.

Can I do something to limit the operator-name? I need ignoring the range of symbols if it is not a separate word. For example, to translate `tan`, but ignore this symbols in `arctan`.

Thanks

**Comment by tsengwoody** [comment]
OK, I will fix this issue by sorting character of length rule by length.
When longer length of character rule is before shorter one, It should solve this fix.

**Comment by tsengwoody** [comment]
I fixed this bug please test it.
