### ISSUE TITLE
Automatic Detection of MathML

### ISSUE THREAD

**Issue by gurfatehsingh67** [tsengwoody/Access8Math#28]
Hi,
I am designing new pdfs that contain MathML instead of just math images. I have been using your plugin with NVDA.
I have an issue where students gets confused as the NVDA starts dictating actual math content, and when we press space it disctates as Maths.
Can we modify the plugin, so NVDA automatically detects the Math and we dont have to press spacebar everytime.

**Comment by tsengwoody** [comment]
I don’t know what you mean, we will enter the interactive mode by pressing space.
Do you want to directly enter the interactive mode when encountering math content?

**Comment by gurfatehsingh67** [comment]
Yes, I want NVDA to start in interactive mode automatically without pressing speacebar.
As if we do not press spacebar, NVDA starts speaking the actual mathml for example: <mathml xmlns="http://www.... which is confusing for vision impaired students. 
Is there any settings that could be updated to enable that?
Thanks.

**Comment by tsengwoody** [comment]
> As if we do not press spacebar, NVDA starts speaking the actual mathml
  Can you give and example file?Is it MathML in PDF?
  In browser, NVDA starts speaking the all content(text) converted from MathML, not MathML code
