### ISSUE TITLE
Some translatable strings are not included in the translation template

### ISSUE THREAD

**Issue by cary-rowen** [tsengwoody/Access8Math#29]
Under the Access8math submenu, there are two menu titles "Write..." and "Localization..." which are not included in the translatable template("Access8math.pot"). Can you check?

**Comment by Futyn-Maker** [comment]
Hello! If you're using "poedit", you can use "Update from the source code" in "catalog" submenu.

**Comment by cary-rowen** [comment]
Thanks @Futyn-Maker. I have realized this, but thank you very much for your reminder.
