### ISSUE TITLE
Access8Math results in the error when using braille display

### ISSUE THREAD

**Issue by Futyn-Maker** [tsengwoody/Access8Math#31]
Hello! I'm using NVDA Beta, so I can know about all NVDA's errors by listening the sound beep.
I've noticed that access8Math results in error when using braille display. When I connect my braille display (Focus 40 Blue) and press any key in this, NVDA returns such error:
```
ERROR - scriptHandler._getObjScript (18:44:40.021) - braille._BgThread (18592):
Traceback (most recent call last):
  File "scriptHandler.pyc", line 59, in _getObjScript
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\__init__.py", line 551, in getScript
    (len(gesture.modifierNames) == 0 or (len(gesture.modifierNames) == 1 and "shift" in gesture.modifierNames)) \
AttributeError: 'KeyGesture' object has no attribute 'modifierNames'
```

Can it be fixed?

Thanks

**Comment by tsengwoody** [comment]
Please test this. I will update to github if it is OK.
https://accessibility.twvip.org/nvda-addon/Access8Math-dev

**Comment by Futyn-Maker** [comment]
Thanks! It seems to work correct now.
