### ISSUE TITLE
Alt+S gesture should be modified

### ISSUE THREAD

**Issue by CyrilleB79** [tsengwoody/Access8Math#32]
Access8Math 3.0 is using Alt+S as a shortcut in any edit field.

Alt+letter are usually reserved to access menu items or dialog box items such as checkboxes, buttons, etc. Since edit field may be encountered everywhere, You should rather choose a gesture using the NVDA key to avoid conflicting with any windows or application native shortcut.

I have encountered this issue in the search dialog box of PoeEdit. There is an edit field where I type the text I want to find. Then I have pressed Alt+S to activate the "Suivant" button, i.e. "Next" in French localization. But instead of activating the button, the Access8Math feature has been toggled.

Thanks.

**Comment by tsengwoody** [comment]
OK. I will think how to modified it.
It was designed as alt+f because the shortcut keys were frequently pressed during edit content, so I chose one key + letter for shortcut.
Maybe it will be modified to using configure turn on/off mode to solution this issue.

**Comment by cary-rowen** [comment]
Yes, another scenario is that the Save button in the Save File As dialog box uses ALT + S as the accelerator

**Comment by CyrilleB79** [comment]
I am also just realizing that there are other alt+letter shortcuts that are added by the add-on in any edit field and thus potentially conflicting with accelerator keys.
Trying in notepad, I have found: alt+H, alt+I, alt+L, alt+M and alt+S.

Please also beware that such simple shortcuts may also conflict with other add-ons. E.g. alt+upArrow or alt+downArrow is used in SentenceNav from @mltony.
IMO, dealing with LaTeX in edit fields is something rather specific. Thus a general shortcut such as alt+letter is not suitable for this task. In comparison, navigating to previous/next sentence (the feature of SentenceNav add-on) is much more generic so it is suitable to be used in any edit field with a common shortcut.

I would recommend activating these shortcuts only in a specific mode (disabled by default), use layered key commands or leave these shortcuts unassigned by default and ask interested users to assign them a gesture according to their own preferences and constraints. Two of these 3 solutions may be implemented since they may be complementary.

**Comment by tsengwoody** [comment]
I develope features: using configure turn on/off mode to solution this issue.
in General Settings -> Using NVDA+alt+letter gesture to active action: Whether shortcut key needs to be added with NVDA key when write mixed content in edit field
This toggle on/off shortcut can set in NVDA Input gestures

**Comment by CyrilleB79** [comment]
Thanks @tsengwoody for your effort to solve the issues of conflicting shortcuts.

Unfortunately, if I activate NVDA key in the general settings of A8M, I get conflict with the read current sentence feature of SentenceNav add-on from @mltony.

As @mltony wrote in #34, it is not always possible to avoid all the conflicts between add-ons. However, I feel that math writting is a very specific task, actually more specific than @mltony's navigation add-ons. And binding A8M math writing scripts to edit controls that are very common controls may create more conflicts with more general add-ons.

IMO, you should really create a "math writing" layer or mode where you bind dynamically all the scripts dedicated to math writing. This would reduce conflicts and ensure that A8M scripts are prioritized when one wants to write math.
Dynamic gesture binding can be done by using the `bindGesture` method instead of defining the script's gesture in the `@script` decorator.

Also I cannot use F12, shift+F11 and shift+F12 in shortcut mode since they are stolen by Speech History from @jscholes. If however you implement dynamical script binding, you may preempt these gestures when you activate shortcut mode.
You may take example of layered commands in [Easy Table Navigator](https://github.com/Oreonan/EasyTableNavigator-1) originally developed by @josephsl and now maintained by @Oreonan.

**Comment by tsengwoody** [comment]
Access8Math 3.1 implement Dynamic gesture binding in math writing scenario.
You can activate/deactivate write/block navigate/shortcut gesture by toggle gesture.
This toggle gesture can be changed in input gesture.

**Comment by CyrilleB79** [comment]
Hi Woody

Thanks for this implementation of dynamic key binding. Having a possibility to enable or disable specific gesture set (writing gestures, bloc navigation gestures or shortcut gestures) is really appreciated.

I have many remarks regarding this new version:

### An issue is remaining where the activated gesture set does not take priority over the existing gestures.
I take an example.

#### Steps to reproduce:
1. I have Access8Math and Speech History add-ons instaalled
2. I start with shortcut gestures disabled
3. I go to an edit field (e.g. notepad) and press F12
4. I press alt+S to enable the shortcut gesture set.
5. I press F12

#### Actual result:
* At step 3., a beep is heard, which means that the shortcut of Speech History is executed. This is expected since A8M shortcut gestures are disabled.
At step 5., a beep is heard, which means that the shortcut of Speech History is executed. I would have expected A8M's shortcut 12 to be executed since A8M shortcut gestures are enabled.

#### Expected result:
* At step 3., a beep is heard, which means that the shortcut of Speech History is executed. This is expected since A8M shortcut gestures are disabled.
At step 5., A8M's shortcut 12 should be executed (insert the LaTeX expression in the 12th slot) since A8M shortcut gestures are enabled and should take priority over the other shortcuts.

### Documentation
It seems to me that the options "Activate write gesture by default" and similar are not described in the help document.

### Option naming
Replacing "by default" by "at startup" or "at NVDA startup" would be more precise. Indeed, I have tried to uncheck "Activate write gestures by default" and I was surprised not to have it already deactivated.

### Shortcut conflicts with alt+letter gestures
This one is more a personal opinion. But again, I think that having alt+letter shortcut active by default is not a good idea since alt+letter shortcut are usually shortcuts reserved to access menu and dialog box items. They are frequent in Windows and applications and exist even when NVDA is not running (this is a Windows standard). Do not forget that some people use A8M only to read math content and that they do not use at all the writing features.
For now in A8M, the following shortcut key are active by default: alt+w, alt+s and alt+n, as well as write gestures (alt+h, alt+i, alt+l, alt+m) since write gestures are enabled by default.
To solve this issue, you should:
   * "Activate write gesture by default" and "Activate shortcut gesture by default" should be unchecked in the default config.
   * Change alt+n, alt+s and alt+w to shortcuts that are more complex than alt+letter shortcuts. Ideally shortcus using NVDA key would be adapted since you are sure that they are not used natively by Windows or an application. An interesting solution could be also to activate all shortcut, bloc navigation and writing gesture with a single shortcut; this would allow to spare key combination and may be easier for the user to press one shortcut than rather 3.

### Reduce the number of shortcuts activated by default
Also another personal opinion: Having shortcut gestures activated by default is not a good idea, since function keys are remapped by default. For example in notepad, with A8M default settings, I am surprised not to be able to use the very common F3 and shift+F3 shortcuts to search forward or backward.

### A8M writing capability in more edit fields
It would be interesting to be able to use writing, block nav and shortcut gestures in more edit field, e.g. in Notepad++. However, for this to be implemented, You should resolve the issues related to "Shortcut conflicts with alt+letter gestures" and "Reduce the number of shortcuts activated by default"


I hope this feedback can be constructive and not disturb you too much!

**Comment by tsengwoody** [comment]
> An issue is remaining where the activated gesture set does not take priority over the existing gestures.
I checked this issue and this issue is from behavior of NVDA, gesture priority is: GlobalPlugin > chooseNVDAObjectOverlayClasses object > NVDA built-in gestures
I can't overlay GlobalPlugin gesture in chooseNVDAObjectOverlayClasses object
I can only overlay built-in gestures in chooseNVDAObjectOverlayClasses object
> An interesting solution could be also to activate all shortcut, bloc navigation and writing gesture with a single shortcut; this would allow to spare key combination and may be easier for the user to press one shortcut than rather 3.
I think it’s better to keep the three separate togglees, because it’s possible that you only need to write shortcut without block navigation shortcut or need indentNav when writing LaTeX
I will try to adjust Access8Math to include your suggestions.
Thank your suggestions.

**Comment by CyrilleB79** [comment]
Thank you for your answer.

> > An issue is remaining where the activated gesture set does not take priority over the existing gestures.
> I checked this issue and this issue is from behavior of NVDA, gesture priority is: GlobalPlugin > chooseNVDAObjectOverlayClasses object > NVDA built-in gestures
> I can't overlay GlobalPlugin gesture in chooseNVDAObjectOverlayClasses object
> I can only overlay built-in gestures in chooseNVDAObjectOverlayClasses object

Maybe you could bind a global gestures rather than an object overlay. You could then call gesture.send() if the focus is not in an edit field. You could even think to trigger and untrigger the shortcut gesture binding on focus events. But these are just thoughts and maybe I have not seen side effects of this way to do.

> > An interesting solution could be also to activate all shortcut, bloc navigation and writing gesture with a single shortcut; this would allow to spare key combination and may be easier for the user to press one shortcut than rather 3.
> I think it’s better to keep the three separate togglees, because it’s possible that you only need to write shortcut without block navigation shortcut or need indentNav when writing LaTeX

OK no problem, it was just a suggestion.

> I will try to adjust Access8Math to include your suggestions.

Many many thanks for taking my feedback into consideration!

**Comment by tsengwoody** [comment]
Access8Math 3.2 has added the feature discussed in this issue.

**Comment by CyrilleB79** [comment]
Thanks!
