### ISSUE TITLE
Access8Math making NVDA read out <mphantom>

### ISSUE THREAD

**Issue by amirah-learn** [tsengwoody/Access8Math#38]
### Steps to reproduce:

1. Go to https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mphantom in Firefox or Chrome
2. Navigate to examples section
3. "rendering in you browser:" will read out "x plus y plus z"
4. Disable **Access8Math**
5. Restart NVDA
6. Navigate back to examples section
7. "rendering in you browser:" will read out "x plus z"

### Actual behavior:

- Reads out "X +       Z" as "x plus y plus z" with **Access8Math** enabled
- Reads out "X +       Z" as "x plus z" with **Access8Math** disabled
- This is reading out the `<mphantom> y + </mphantom>` when **Access8Math** enabled

### Expected behavior:

- Read out "X +       Z" as "x plus z" with **Access8Math** enabled or disabled
- Should not read out `<mphantom>` in any case

_Note: Chrome doesn't support `<mphantom>` thus "y +" will still appear but still shouldn't be read_

#### NVDA version:

2021.1

#### Windows version:

Windows 10 (64-bit)

#### Name and version of other software in use when reproducing the issue:

Chrome (93.0.4577.63)
Firefox (92.0)

**Comment by tsengwoody** [comment]
commit # e9adb5c
