### ISSUE TITLE
Is there a way to eliminate item numbers from spoken output

### ISSUE THREAD

**Issue by RichCaloggero** [tsengwoody/Access8Math#4]
This is a very well done add-on. It is extremely configurable and easy to install.

Wondering if there is a way to eliminate item numbers when navigating. To some, these might be useful, but to an advanced user, including item numbers will slow them down. Also, if the actual expression contains a numeric constant, then speaking item number followed by the actual constant from the expression might be confusing.

**Comment by tsengwoody** [comment]
Thanks for your compliment.
About eliminating item numbers from spoken output:
Access8Math will not speak item numbers when General settings->Read of auto-generated meaning checkbox is unchecked.
