### ISSUE TITLE
Add ability to filter symbols in Localization/unicode dictionary

### ISSUE THREAD

**Issue by nvdaes** [tsengwoody/Access8Math#46]
Sometimes it's needed to localize symbols progressively as they appear, and a feature to search the English text corresponding to them would be very helpful.
Thanks

**Comment by tsengwoody** [comment]
Access8Math 3.2 have been already added this feature.

**Comment by nvdaes** [comment]
Thanks a lot.

2022-01-01 2:37 GMT+01:00, Tseng Woody ***@***.***>:
