### ISSUE TITLE
the math interacting feature breaks arrow keys!

### ISSUE THREAD

**Issue by denizsincar29** [tsengwoody/Access8Math#54]
the access8math, when interacting with the math object, says nothing when i press arrows, but it beeps when reached right and left ends. but when i finish interacting, arrow keys are not speaking letters and lines in the text fields till i restart nvda.

**Comment by tsengwoody** [comment]
What is the windows version and NVDA version?

**Comment by denizsincar29** [comment]
windows 11, nvda last stable. issue solved however sometimes it is occurring again.issue solved i think. nvda last stable, win11

**Comment by cary-rowen** [comment]
The "NVDA global commands extension" is known to conflict with access8math.
