### ISSUE TITLE
all the writing features straight up don't work

### ISSUE THREAD

**Issue by albluc24** [tsengwoody/Access8Math#55]
I have installed the addon and, either through the stable release or through the addon folder here, none of the writing gestures show up in the nvda gestures manager. 
Moreover, alt+m in any sort of text field does not produce any effect and I cannot see any way to get to the write dialog. Having a quick look at global plugins __init__.py I see the write tool is imported, but i can't see any code that registers or uses it. I feel like I am missing something extremely basic, what is it?
my nvda version is 2021.3.1, I am running windows 11 Version 21H2 (OS build  22000.588)

**Comment by tsengwoody** [comment]
This issue is because windows 11 has changed the UI of the editing area.
Access8Math next version will provide a built-in and usable traditional editing area to use writing features.

**Comment by tsengwoody** [comment]
# 32e303b commit is added built-in editor using traditional editing area(tools->Access8Math->editor)
