### ISSUE TITLE
Data_folder should not be copied directly in rawIntoReview

### ISSUE THREAD

**Issue by cary-rowen** [tsengwoody/Access8Math#59]
Hi,

Imagine if there is such a file as "d:\document.txt", then the line ```shutil.copytree(data_folder, review_folder)``` will copy all files under "D:\" to review_folder.

You may be doing this because you want to load external resource files such as "data_folder\images",
however, could we have a better way? Is it even possible to ditch the workspace?

For example, is it possible to save the documentation and required js modules to a separate directory when doing the export?

Thanks

**Comment by tsengwoody** [comment]
Commit 3c4959
