### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ManolloGuedes** [tsengwoody/Access8Math#6]
Hello, I would like to email you, but as I don't have your contact information I just decided to open this issue.

I really appreciated this project and your initiative to provide it to the blind community.

I am doing a master's research related to math navigation using screen readers so my idea is to understand your code and try to propose an alternative version based on it. So, I wonder if you have code documentation.

Please, let me know :D thanks

**Comment by tsengwoody** [comment]
Sorry, there is no document fr this addon program structure.
If you need how addon work you can research A8M_PM_3.py
the core of this addon is in addon/globalPlugins/MathMlReader/A8M_PM_3.py, which parses MathML into tree structure and serialized text.
Finally use NVDA's API to read and speech the parsed structure.
You can send email to tsengwoody.tw@gmail.com for contant me.

**Comment by ManolloGuedes** [comment]
Hello :D 
thanks for this fast answer.
Okay then, I will save your email to make contact about my version and future questions that may appear.

Thanks again :)
