### ISSUE TITLE
No support for MathML menclose element

### ISSUE THREAD

**Issue by thrintuim** [tsengwoody/Access8Math#66]
## Steps to reproduce
1. navigate to the [menclose MDN article](https://developer.mozilla.org/en-US/docs/Web/MathML/Element/menclose)
2. Using NVDA with Access8Math installed navigate to the `notation` portion of the Attributes section.
3. Read through the table of possible `@notation` values, noting the announcement of math in column "Rendering in your browser"
4. Notice that NVDA will announce "a squared plus b squared" regardless of notation used in the `menclose` element.

## Expected behavior
Some mention of the enclosing notation is expected. JAWS 2022 provides the following announcements for the math expressions in the table based on their notation.
notation="longdiv": a squared + b squared, under long division symbol  MathContent 
notation="actuarial": a squared + b squared, under actuarial symbol  MathContent 
notation="radical": a squared + b squared, under radical symbol  MathContent 
notation="box": a squared + b squared, surrounded by box  MathContent 
notation="roundedbox": a squared + b squared, surrounded by rounded box.  MathContent 
notation="circle": a squared + b squared, surrounded by circle  MathContent 
notation="left": a squared + b squared, with line on the left  MathContent 
notation="right": a squared + b squared, with line on the right  MathContent 
notation="top": a squared + b squared, with line on the top  MathContent 
notation="bottom": a squared + b squared, with line on the bottom  MathContent 
notation="updiagonalstrike": a squared + b squared, covered by up diagonal strike  MathContent 
notation="downdiagonalstrike": a squared + b squared, covered by down diagonal strike  MathContent 
notation="verticalstrike": a squared + b squared, covered by virtacal strike  MathContent 
notation="horizontalstrike": a squared + b squared, covered by horizontal strike  MathContent 
notation="madruwb": a squared + b squared, madruwb  MathContent 
notation="updiagonalarrow": a squared + b squared  MathContent 
notation="phasorangle": a squared + b squared  MathContent

NVDA + MathPlayer output is as follows:
notation="longdiv": long division symbol enclosing   a  squared   plus   b  squared   end symbol 
notation="actuarial": actuarial symbol enclosing   a  squared   plus   b  squared   end symbol 
notation="radical": the square root of   a  squared   plus   b  squared    
notation="box": begin box   a  squared   plus   b  squared   end box 
notation="roundedbox": begin rounded box   a  squared   plus   b  squared   end rounded box 
notation="circle": begin circle   a  squared   plus   b  squared   end circle 
notation="left": line left of   a  squared   plus   b  squared   end line 
notation="right": line right of   a  squared   plus   b  squared   end line 
notation="top": line above   a  squared   plus   b  squared   end line 
notation="bottom": line below   a  squared   plus   b  squared   end line 
notation="updiagonalstrike": cross out enclosing   a  squared   plus   b  squared   end crossout 
notation="downdiagonalstrike": cross out enclosing   a  squared   plus   b  squared   end crossout 
notation="verticalstrike": cross out enclosing   a  squared   plus   b  squared   end crossout 
notation="horizontalstrike": cross out enclosing   a  squared   plus   b  squared   end crossout 
notation="madruwb": a  squared   plus   b  squared 
notation="updiagonalarrow": math m l error   long division symbol enclosing   a  squared   plus   b  squared   end symbol   end math m l error 
notation="phasorangle": a  squared   plus   b  squared 

The `menclose` element is the only way to get long division symbols to render in Firefox. This is the same for MathJax, unless you add the extension that provides support for mlongdiv, mstack, etc. Obviously neither MathPlayer nor JAWS provide support for all notations but long division, crossouts, shapes, and lines would go a long way.

**Comment by tsengwoody** [comment]
commit d73a89

**Comment by thrintuim** [comment]
There is a slight type on line 700 in A8M_PM.py causing NVDA to announce "notation:line on button" for `@notation="bottom"`. Tested all the other notation type and they sound great!
