### ISSUE TITLE
mspace element is announced as "empty"

### ISSUE THREAD

**Issue by thrintuim** [tsengwoody/Access8Math#67]
## Steps to reproduce
1. create an html page that contains a MathML equation that has a `mspace` element in it
2. use NVDA with Access8Math installed to announce the equation
3. Note that the `mspace` element is announced as empty

## Expected behavior
`mspace` element is ignored in announcement, or at most signifies a brief pause in announcement. JAWS 2022 ignores `mspace`. NVDA with MathPlayer 4 seems to pause briefly for `mspace` but it is otherwise ignored even with punctuation set to "all"

**Comment by tsengwoody** [comment]
Improved in the 8f916b commit
