### ISSUE TITLE
very limited support for `mmultiscripts`

### ISSUE THREAD

**Issue by thrintuim** [tsengwoody/Access8Math#68]
## Steps to reproduce
1. navigate to thrintuim.github.io/mmultiscripts.html
2. use NVDA with Access8Math installed to read through the page.
3. Notice that the equation under the heading no none arguments announces as: "clickable      left script  base  order0left down mark  pre subscript  order0left up mark  pre superscript  end script", with no mention of the post scripts
4. Notice that all other equations are announced only as clickable.

## Expected results
For each math equation in the page NVDA + MathPlayer 4 announces the following:
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   upper   pre superscript   post-scripts   lower   post subscript   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   upper   pre superscript   post-scripts   lower   post subscript   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   post-scripts   lower   post subscript   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   upper   pre superscript   post-scripts   lower   post subscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   upper   pre superscript   post-scripts   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   upper   pre superscript   post-scripts   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   post-scripts   lower   post subscript   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   upper   pre superscript   post-scripts   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   post-scripts   lower   post subscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   upper   pre superscript   post-scripts   lower   post subscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   post-scripts   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   post-scripts   lower   post subscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   post-scripts   upper   post superscript   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   lower   pre subscript   post-scripts   end multi-scripts 
clickable    multi-scripts   with base   base   and 1 prescript and 1 post-script   pre-scripts   upper   pre superscript   post-scripts   end multi-scripts

JAWS 2022 is not helpful for determining how this element should be annoucned. JAWS 2022 announces the content of `mmultiscripts` child elements in document order with no mention of any kind of super or subscripting. `mmultiscripts` seems like it would be the preferred way to write combinations and permutations, e.g. <sub>n</sub>P<sub>k</sub>.

**Comment by tsengwoody** [comment]
Improved in the 8f916b commit
