### ISSUE TITLE
Row lines and Column lines not announced for `mtable` elements

### ISSUE THREAD

**Issue by thrintuim** [tsengwoody/Access8Math#69]
## Steps to Reproduce

1. navigate to https://thrintuim.github.io/mtable%20with%20row%20and%20column%20lines.html
2. use NVDA with Access8Math installed to read through the page.
3. Notice that the row and column lines are not mentioned at all by NVDA

## Expected Results

This is more a suggestion than an actual bug. Neither JAWS, NVDA w/ MathPlayer, or NVDA w/ MathCAT announce row and column lines in `mtable` elements. Perhaps the row and column lines could be announced when the dimensions of the table are announced. This would be important when discussing augmented matrices, or when a row line is used in a `mtable` representing stacked arithmetic.

**Comment by tsengwoody** [comment]
I'm not quite sure what you mean. Are you want to not speak row1, row2, and row3?
current speak:open tablehas3row3column row1  column1  1  column2  0  column3  0   row2  column1  0  column2  1  column3  0   row3  column1  0  column2  0  column3  1   end table close
change to speak: open tablehas3row3column column1  1  column2  0  column3  0 column1  0  column2  1  column3  0 column1  0  column2  0  column3  1   end table close
