### ISSUE TITLE
Possible inefficiency in symbol_translate method

### ISSUE THREAD

**Issue by thrintuim** [tsengwoody/Access8Math#71]
https://github.com/tsengwoody/Access8Math/blob/9fc55e707a3deb44d235318226ac13ea40356043/addon/globalPlugins/Access8Math/A8M_PM.py#L397

There very well might be a good explanation for why this method is structured the way it is but it seems like it could be reduced to:
```
def symbol_translate(self, string):
    return self.mathcontent.symbol.get(string, string)
```
It seems like the same could be done for the braille_symbol_translate method but there may be something that I'm missing there.

**Comment by tsengwoody** [comment]
I think it makes a little difference in compound symbols in one node.
For example "∽∿" will translate to "reversed tilde sine wave" now.
but using dictionary get method will not translated in this case.
