### ISSUE TITLE
Access8math causes Braille keyboard input to fail

### ISSUE THREAD

**Issue by cary-rowen** [tsengwoody/Access8Math#73]
You might be able to test this with the [pcKbBrl add-on](https://nvdacn.com/index.php/archives/938/).

* Input table:Unified English Braille Code grade 1
* Try typing English letters.

**Comment by tsengwoody** [comment]
You need to disable/inactive the shortcut mode (NVDA+Alt+S) and Greek letter input mode (NVDA+Alt+G) in the writing feature of Access8Math.
