### ISSUE TITLE
The settings dialogue of addon are not available for viewing and modifying

### ISSUE THREAD

**Issue by Kostenkov-2021** [tsengwoody/Access8Math#78]
When trying to go to the addon settings to make some changes using the following way NVDA menu\tools\access 8 Math\settings... the settings dialogue are not appeared. The screen reader is silent. Don't reacted on the keyboard commence apart going to the desktop.

Operating system – windows 11;
NVDA version - 2023.1;
Addon version - 3.5.

**Comment by tsengwoody** [comment]
Please provide log

**Comment by Kostenkov-2021** [comment]
INFO - __main__ (12:36:32.452) - MainThread (12556):
Starting NVDA version 2023.1
INFO - core.main (12:36:32.484) - MainThread (12556):
Config dir: C:\Users\koste\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (12:36:32.500) - MainThread (12556):
Loading config: C:\Users\koste\AppData\Roaming\nvda\nvda.ini
INFO - core.main (12:36:32.610) - MainThread (12556):
Windows version: Windows 11 22H2 (10.0.22621) workstation AMD64
INFO - core.main (12:36:32.610) - MainThread (12556):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (12:36:32.610) - MainThread (12556):
Using comtypes version 1.1.11
INFO - core.main (12:36:32.610) - MainThread (12556):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (12:36:33.001) - MainThread (12556):
Loaded synthDriver vocalizer_expressive2
WARNING - mathPres.initialize (12:36:33.014) - MainThread (12556):
MathPlayer 4 not available
INFO - core.main (12:36:33.014) - MainThread (12556):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (12:36:33.014) - MainThread (12556):
Braille input initialized
INFO - braille.initialize (12:36:33.014) - MainThread (12556):
Using liblouis version 3.24.0
INFO - braille.initialize (12:36:33.014) - MainThread (12556):
Using pySerial version 3.5
INFO - braille.BrailleHandler.setDisplayByName (12:36:33.024) - MainThread (12556):
Loaded braille display driver 'noBraille', current display has 0 cells.
INFO - core.main (12:36:33.232) - MainThread (12556):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (12:36:33.323) - UIAHandler.UIAHandler.MTAThread (10512):
UIAutomation: IUIAutomation6
INFO - NVDAHelperLocal (12:36:33.441) - UIAHandler.UIAHandler.MTAThread (10512):
Thread 10512, build\x86\UIARemote\UIARemote.cpp, initialize, 145:
Registered C:\Program Files (x86)\NVDA\lib\2023.1\Microsoft.UI.UIAutomation.dll.manifest

INFO - NVDAHelperLocal (12:36:33.441) - UIAHandler.UIAHandler.MTAThread (10512):
Thread 10512, build\x86\UIARemote\UIARemote.cpp, initialize, 150:
Microsoft.UI.UIAutomation is available

INFO - external:globalPlugins.MathCAT.MathCAT.MathCAT.__init__ (12:36:35.521) - MainThread (12556):
MathCAT Rules dir: C:\Users\koste\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\Rules
WARNING - globalPlugins.Access8Math.dialogs (12:36:36.396) - MainThread (12556):
MathPlayer 4 not available
INFO - external:globalPlugins.MathCAT.MathCAT.MathCAT.__init__ (12:36:36.397) - MainThread (12556):
MathCAT Rules dir: C:\Users\koste\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\Rules
WARNING - globalPlugins.Access8Math.interaction (12:36:36.408) - MainThread (12556):
MathPlayer 4 not available
INFO - external:globalPlugins.MathCAT.MathCAT.MathCAT.__init__ (12:36:36.408) - MainThread (12556):
MathCAT Rules dir: C:\Users\koste\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\Rules
INFO - external:globalPlugins.MathCAT.MathCAT.MathCAT.__init__ (12:36:37.027) - MainThread (12556):
MathCAT Rules dir: C:\Users\koste\AppData\Roaming\nvda\addons\MathCAT\globalPlugins\MathCAT\Rules
WARNING - external:globalPlugins.Access8Math (12:36:37.029) - MainThread (12556):
MathPlayer 4 not available
INFO - core.main (12:36:37.048) - MainThread (12556):
NVDA initialized
WARNING - appModuleHandler._warnDeprecatedAliasAppModule (12:36:45.286) - MainThread (12556):
Importing appModules.textinputhost is deprecated, instead import appModules.windowsinternal_composableshell_experiences_textinput_inputapp.
ERROR - unhandled exception (12:37:20.957) - MainThread (12556):
Traceback (most recent call last):
  File "wx\core.pyc", line 3407, in <lambda>
  File "gui\blockAction.pyc", line 65, in funcWrapper
  File "gui\__init__.pyc", line 165, in _popupSettingsDialog
  File "C:\Users\koste\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\dialogs.py", line 400, in __init__
    super().__init__(parent, initialCategory)
  File "gui\settingsDialogs.pyc", line 471, in __init__
  File "gui\settingsDialogs.pyc", line 201, in __init__
  File "gui\settingsDialogs.pyc", line 540, in makeSettings
  File "gui\settingsDialogs.pyc", line 649, in _doCategoryChange
  File "gui\settingsDialogs.pyc", line 577, in _getCategoryPanel
  File "gui\settingsDialogs.pyc", line 335, in __init__
  File "gui\settingsDialogs.pyc", line 345, in _buildGui
  File "C:\Users\koste\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\dialogs.py", line 162, in makeSettings
    available_languages_dict = {k: map[k] for k in available_languages}
  File "C:\Users\koste\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\Access8Math\dialogs.py", line 162, in <dictcomp>
    available_languages_dict = {k: map[k] for k in available_languages}
KeyError: 'ru_RU'
ERROR - eventHandler.executeEvent (12:37:30.045) - MainThread (12556):
error executing event: UIA_notification on <NVDAObjects.UIA.UIA object at 0x08A4A070> with extra args of {'notificationKind': 2, 'notificationProcessing': 1, 'displayString': 'Закрытие вкладки', 'activityId': 'ClosingTab'}
Traceback (most recent call last):
  File "eventHandler.pyc", line 300, in executeEvent
  File "eventHandler.pyc", line 101, in __init__
  File "eventHandler.pyc", line 108, in next
  File "eventHandler.pyc", line 136, in gen
  File "NVDAObjects\__init__.pyc", line 429, in _get_treeInterceptor
  File "treeInterceptorHandler.pyc", line 32, in getTreeInterceptor
  File "UIAHandler\browseMode.pyc", line 518, in __contains__
  File "monkeyPatches\comtypesMonkeyPatches.pyc", line 32, in __call__
_ctypes.COMError: (-2147024809, 'Параметр задан неверно.', (None, None, None, 0, None))
INFO - watchdog.waitForFreezeRecovery (12:37:48.243) - watchdog (8552):
Starting freeze recovery after 0.500368899999998 seconds.
INFO - watchdog.waitForFreezeRecovery (12:37:48.621) - watchdog (8552):
Recovered from freeze after 0.8787506000000036 seconds.

**Comment by tsengwoody** [comment]
The issue has been fixed, and you can try using the latest preview version to

**Comment by tsengwoody** [comment]
[download](https://accessibility.twvip.org/nvda-addon/Access8Math-dev)
