### ISSUE TITLE
Access8Math ignores localization and read formulas and cymbls in English

### ISSUE THREAD

**Issue by Kostenkov-2021** [tsengwoody/Access8Math#79]
When the add-on  is  using in non-English language, it ignores 
localization files which are in the right place in 
"C:\Users\userfolder\AppData\Roaming\nvda\addons\Access8Math\locale "and 
the formula or symbol is voicing in English.

Operating system - windows 11
Add-on version - 3.5
NVDA version - 2023.1

**Comment by tsengwoody** [comment]
If you want to generate MathML speech or braille output in different
languages, you'll need to create a Unicode Dictionary (unicode.dic) and
Mathematics Rules (math.rule). This can be done using the GUI editor in
Access8Math -> Localization, or by referring to the
globalPlugins/Access8Math/locale in the addon folder.
The "Unicode Dictionary" enables you to customize speech or braille
output for symbols and characters, converting them to text.
The "Mathematics Rules" allow you to customize speech or braille output
for different types of mathematics.

If you're willing, I would be happy to include your completed
speech/braille unicode.dic and math.rule in the addon. This way, future
releases of the addon will have your language translation available for
selection in the settings.

**Comment by Kostenkov-2021** [comment]
Sorry, I meant that character translations are already in the folder, but when reading math symbles they are ignored.

**Comment by tsengwoody** [comment]
Have you selected the correct language option in the Access8Math settings?
Can you provide me with an example that includes configuration/MathML document or additional information? Is the latest version experiencing this problem?
[download](https://accessibility.twvip.org/nvda-addon/Access8Math-dev)
