### ISSUE TITLE
Access8Math does not read MathML content in Chrome

### ISSUE THREAD

**Issue by MohamedNoordin** [tsengwoody/Access8Math#87]
For the first time I tried Access8Math, it worked very well without problems in Google Chrome, but when I disabled the add-on and then re-enabled it, it doesn't speak out MathML content in Chrome when I move over a line that contains MathML content, although the navigator object role is expressed as "MATH". Even when I hit the space bar for the dialog or the popup to open on the MathML element, nothing happens. Now, when I browse MathML content, NVDA speaks none. Peace and quiet. However, I tried to install both of MathCAT and MathPlayer, I tried to switch the math reader speach source to both of MathCAT and MathPlayer, also without a result.  
When I tried to read math content in Edge using Access8Math, it reads MathML content without any problem. The problem lies in Google Chrome web browser.
I am not sure what the problem is, but I am sure that I need it to work instantaneously.  
I can provide any relavant logs/documentations once requested.

**Comment by tsengwoody** [comment]
Please confirm if the issue of not being able to read math content in Chrome persists when you disable Access8Math and switch to using MathPlayer.
I haven't happend this problem after disabling and then reactivating Access8Math on my end. Perhaps you could provide the log for me to check what happen.

**Comment by MohamedNoordin** [comment]
I'm sorry, but the functionality only returned after closing all Chrome instances and opening a new clean session. Simply closing and reopening the specific Chrome instance/session was ineffective.  
Unfortunately, I don't have relevant logs to share at this time. However, this suggests a potential instability issue within either Chrome, NVDA, or Access8Math.  
Since the issue seems resolved for now, I'll close this issue. If I encounter the behavior again, I'll reopen a new issue with relevant logs attached for further investigation.  
Thank you for your understanding.

**Comment by alisa-kalina** [comment]
> Please confirm if the issue of not being able to read math content in Chrome persists when you disable Access8Math and switch to using MathPlayer. I haven't happend this problem after disabling and then reactivating Access8Math on my end. Perhaps you could provide the log for me to check what happen.

Hello!
Unfortunately, I have the same problem with addon in both chrome and Microsoft browsers. NVDA just speaks nothing when any MathML content appears. I've allready tried all NVDA versions from 2024.1 to 2024.3, all last versions of addon, but the effect is the same. I tested different Wikipedia articles and other websites. Befor I had a Laptop with Windows-8 and access8math worked without problems, but now on Windows-11 it doesn\t read anything. I installed also Mathplayer and MathCat, changed access8math settings, but it didn't help. Bellow is the information I can see in Nvda.log file, and i didn't find any errors there.



INFO - globalCommands.script_navigatorObject_devInfo (18:49:11.964) - MainThread (7672):
Developer info for navigator object:
name: None
role: MATH
processID: 9100
roleText: None
states: 
isFocusable: False
hasFocus: False
Python object: <NVDAObjects.IAccessible.ia2Web.Math object at 0x06050050>
Python class mro: (<class 'NVDAObjects.IAccessible.ia2Web.Math'>, <class 'NVDAObjects.IAccessible.ia2Web.Ia2Web'>, <class 'NVDAObjects.IAccessible.IAccessible'>, <class 'NVDAObjects.window.Window'>, <class 'NVDAObjects.NVDAObject'>, <class 'documentBase.TextContainerObject'>, <class 'baseObject.ScriptableObject'>, <class 'baseObject.AutoPropertyObject'>, <class 'garbageHandler.TrackedObject'>, <class 'object'>)
description: None
location: RectLTWH(left=316, top=625, width=44, height=14)
value: ''
TextInfo: <class 'NVDAObjects.IAccessible.IA2TextTextInfo'>
appModule: AppModule(appModuleHandler, appName='chrome', processID=9100)
appModule.productName: 'Google Chrome'
appModule.productVersion: '131.0.6778.205'
appModule.helperLocalBindingHandle: c_long(126962072)
windowHandle: 1181376
windowClassName: 'Chrome_RenderWidgetHostHWND'
windowControlID: 33305824
windowStyle: 1445986304
extendedWindowStyle: 32
windowThreadID: 8744
windowText: 'Chrome Legacy Window'
displayText: ''
IAccessibleObject: <POINTER(IAccessible2) ptr=0x805ef74 at f4ab260>
IAccessibleChildID: 0
IAccessible event parameters: windowHandle=1181376, objectID=-4, childID=-2836
IAccessible accName: None
IAccessible accRole: ROLE_SYSTEM_EQUATION
IAccessible accState:  (0)
IAccessible accDescription: None
IAccessible accValue: ''
IAccessible2 windowHandle: 1181376
IAccessible2 uniqueID: -2836
IAccessible2 role: ROLE_SYSTEM_EQUATION
IAccessible2 states: IA2_STATE_OPAQUE (1024)
IAccessible2 attributes: 'display:math;tag:math;text-align:left;math:\n  <semantics>\n    <mrow class\\="MJX-TeXAtom-ORD">\n      <mstyle displaystyle\\="true" scriptlevel\\="0">\n        <mi>k</mi>\n        <mo>\\=</mo>\n        <mn>3</mn>\n      </mstyle>\n    </mrow>\n    <annotation encoding\\="application/x-tex">{\\\\displaystyle k\\=3}</annotation>\n  </semantics>\n;'
IAccessible2 relations:
