### ISSUE TITLE
Translation of some consts

### ISSUE THREAD

**Issue by Futyn-Maker** [tsengwoody/Access8Math#9]
Hello everybody!

I want to make a Russian translation of rules and symbols of Access8Math, but I found some problems with translation of some consts.

So how can I translate 'sin', 'cos', 'tan' and etc? I see that these consts aren't defined in the const section of unicode.dic. When I do, for example:
```sin\ttranslation\tnone```
I don't get any result.

**Comment by tsengwoody** [comment]
Please check the correctness of MathML notation
You use some editing tools, it may split 'sin' into 3 elements and let Access8Math translate failed. For example:
error:
<math {http://www.w3.org/XML/1998/namespace}lang = "en"><mi>s</mi><mi>i</mi><mi>n</mi><mi>x</mi></math>
correct:
<math {http://www.w3.org/XML/1998/namespace}lang = "en"><mi>sin</mi><mi>x</mi></math>
Is it not the above problem? please provide the test mathml.

**Comment by Futyn-Maker** [comment]
I defined the 'sin' const translation in the unicode.dic file, than I test it by convertion LaTEX to MathML.
The LaTEX code:
```\sin\alpha```
And I get such MathML:
```<math display = "block"><mi>sin</mi><mo>⁡</mo><mi>α</mi></math>```
Well, all correct. But Access8Math read english 'sin' instead of my translation (Russian 'синус'). The translation of MathML is correct.

**Comment by tsengwoody** [comment]
What unicode.dic file you edit?
try to edit unicode_user.dic/math_user.rule file.
I suggest using the ui in the addon to add and edit your language.
1. New language adding...->choice your language->OK
2. General settings...->choice your language->OK
3. Using unicode dictionary... and math rule... UI to edit and click OK button to save it.

**Comment by Futyn-Maker** [comment]
Oh, I've already tryed everything :) The fact is that some consts, such as 'sin', 'cos' and etc are ignored.

In UI i added new symbol, input 'sin' and in the replacement feeld typed my translation. But it get no result. The string after my actions in unicode_user.dic file looks so:
```sin	синус	none```
But it doesn't work...

Are you sure that such consts are not hardly defined in code of addon? Because they aren't defaultly defined in unicode.dic file and are ignored by the addon.

**Comment by tsengwoody** [comment]
OK, I know what happen.
I found the bug and fixed it but forgot to release the new version.
Can you try this version below?
https://accessibility.twvip.org/Access8Math/Access8Math-2.4.nvda-addon
I will release new version if it is OK.

**Comment by Futyn-Maker** [comment]
This version completely doesn't work in my NVDA 2020.2 I've even changed the lastTestedVersion in manifest-file, but the addon have 'pendingInstall' mark which is even after restarted NVDA.

**Comment by Futyn-Maker** [comment]
This version completely doesn't work in my NVDA 2020.2 I've even changed the lastTestedVersion in manifest-file, but the addon have 'pendingInstall' mark which is even after restarted NVDA.

**Comment by Futyn-Maker** [comment]
Already doesn't relevant. I deleted the old version and its OK now.

Well, the translation of consts now works correct, but the new interesting problem is appear. Did You change the format of rules? I imported my rules by the 2.3 version and now Access8Math speaks the number of every item when I listen the formula. For example:
```\sin\alpha + 3```:
```1* sin 2* ⁡ 3* alpha 4* + 5* 3``` (the phrase of NVDA)
Of course, in my native-language translation as I replace it. When I use the English (default) translation, formulas speaks normally.

**Comment by Futyn-Maker** [comment]
In addition, the dialog of settings of math rules doesn't open with following error in the journal:

```ERROR - unhandled exception (12:45:52.779) - MainThread (15536):
Traceback (most recent call last):
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\MathMlReader\__init__.py", line 585, in onMathRule
    gui.mainFrame._popupSettingsDialog(MathRuleDialog, self.language)
  File "gui\__init__.pyc", line 186, in _popupSettingsDialog
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\MathMlReader\dialogs.py", line 508, in __init__
    super(MathRuleDialog, self).__init__(parent)
  File "gui\settingsDialogs.pyc", line 154, in __init__
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\MathMlReader\dialogs.py", line 524, in makeSettings
    self.refresh()
  File "C:\Users\andre\AppData\Roaming\nvda\addons\Access8Math\globalPlugins\MathMlReader\dialogs.py", line 586, in refresh
    self.mathrulesList.Append((item[0], item[1].description,))
AttributeError: 'NoneType' object has no attribute 'description'```

**Comment by Futyn-Maker** [comment]
In conclusion, I've rewritten math.rule file anew and it works normally. Thank You! Now I can say that I're able to translate it completely.

**Comment by tsengwoody** [comment]
Thank your feedback!
math.rule format changed in 2.4 so your export in 2.3 not work when iyou import in 2.4.
If you have finished your translation. Welcome to put your translation via pull request.
I will release new version to fix this bug and hope including your translation.
Thank!

**Comment by Futyn-Maker** [comment]
No, the translation isn't completed yet, I need some help of Russian colleagues to translate some difficult rules. I think I will put my translation soon, so You can release the version without Russian translation or wait bit time.

Thanks.

**Comment by tsengwoody** [comment]
OK! I could wait bit time. ^^

**Comment by Futyn-Maker** [comment]
Can I get an actual PO-file to translate the UI-interface? I took the French file and replaced the translation, but I see that some things already haven't been relevant as this translation for version 2.1.

**Comment by tsengwoody** [comment]
I have updated Repository adding pot file.
https://github.com/tsengwoody/Access8Math/blob/master/Access8Math.pot

**Comment by Futyn-Maker** [comment]
Many thanks.

**Comment by Futyn-Maker** [comment]
And one more question, please. What about Greek capital letters? I see the strange situation.
The LaTEX commands such as `\Alpha`, `\Beta` (with the first capital sign) doesn't interpret correctly. Besides, in the english unicode.dic file there're no capital Greek letters, but there're a lot of duplicates of lowercase letters - almost all Greek lowercase letter are twice in the dictionary. Well, does it make sense to add in my Russian file the capital Greek letters? What about reading of them in general?

**Comment by tsengwoody** [comment]
> The LaTEX comm acturals such as \Alpha, \Beta (with the first capital sign) doesn't interpret correctly (probably it's problem with Mathjax?)
I test LaTEX commands "\Alpha" and actually not correct convert MathML by mathjax.
> What about reading of them in general?
I don`t know how to speech is best too
adding "capital" before speech letter?

**Comment by Futyn-Maker** [comment]
> > I test LaTEX commands "\Alph" and actually not correct convert MathML by mathjax.

OK, I'll wait for fix :)

> > I don`t know how to speech is best too
> > adding "capital" before speech letter?

Good question! I think we can just make the first word of the replacement uppercase, so if the user need to differ the letter, he'll be able to hear the element by spelling, but I'm not sure that it's good idea, too.

And what about duplicates of lowercase Greek letters? Can I delete it in the translation?

**Comment by Futyn-Maker** [comment]
See https://github.com/tsengwoody/Access8Math/pull/10
