### ISSUE TITLE
NVDA+Shift+F10 has become the core gesture of NVDA

### ISSUE THREAD

**Issue by cary-rowen** [tsengwoody/Access8Math#96]
> A new Native Selection mode (toggled by  NVDA+shift+f10 ) is now available in NVDA's browse mode for Mozilla Firefox. When turned on, selecting text in browse mode will also manipulate Firefox's own native selection. Copying text with  control+c  will pass straight through to Firefox, thus copying the rich content, rather than NVDA's plain text representation. Note however that as Firefox is handling the actual copy, NVDA will not report a "copy to clipboard" message in this mode.

See: [nvaccess/nvda#15830](https://github.com/nvaccess/nvda/pull/15830)

**Comment by CyrilleB79** [comment]
Just discovered this one today. I'll unbound A8M's shortcut for my personal usage. But it would be nice to release a new version of A8M which does not uses `NVDA+shift+f10` as a default shortcut.

@tsengwoody could you please take care of this?

**Comment by tsengwoody** [comment]
Maybe Access8Math can determine if the active focus object is the windows file explorer before binding NVDA+Shift+F10, just like how NVDA+Shift+F10 is only active for Native Selection mode when in browse mode?

**Comment by tsengwoody** [comment]
commit 5490c85
