### ISSUE TITLE
Shortcut key conflict `NVDA+alt+S`

### ISSUE THREAD

**Issue by CyrilleB79** [tsengwoody/Access8Math#99]
`NVDA+alt+s` is the new Sound Split shortcut in NVDA 2024.2beta2.

Please use another shortcut for "Toggle shortcut gestures" command to avoid overriding native NVDA commands. Thanks!

**Comment by tsengwoody** [comment]
Thank you for your feedback. I think that the impact is minimal and no adjustment is necessary, because NVDA+alt+s for Access8Math only works within the built-in editor/notepad (Windows 10).
Users can switch to other windows to use the Sound Split feature, or if you have other points or considerations, please let us know.

**Comment by CyrilleB79** [comment]
The shortcut does not only operate in Notepad but in any control having the same edit field type. It happened to me in real-life situation to want to use Sound split while in a code editor and got the A8M shortcut instead.

Since you have developed a dedicated editor for Windows 11 transition, it is not necessary to allow to write math content in Notepad or other such edit fields now IMO.
What do you think of keeping only the A8M editor to write math?

**Comment by CyrilleB79** [comment]
For example, the shortcut also operates in Run window's edit field (Windows+R). But it's just an example among others.

**Comment by tsengwoody** [comment]
> What do you think of keeping only the A8M editor to write math?
I think this is a great idea. I will consider limiting shortcuts to only within the Access8Math editor.

**Comment by tsengwoody** [comment]
Finished by commit #256789

**Comment by cary-rowen** [comment]
I think I will use notepad to open the markdown file and write,
In fact, I am not willing to open the a8m editor to write math, and the a8m editor does not support opening markdown files in the filter of the open dialog. I have to select all types.

**Comment by tsengwoody** [comment]
I will think about whether there's a better way to do it.

**Comment by tsengwoody** [comment]
Added write feature enabled in Access8Math editor, Notepad, and Notepad++ only.
